[package]
name = "vaultls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["native-tls"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]

[dependencies]
reqwest = { version = "0.11.18", default-features = false, features = ["blocking"] }
quick-error = "2.0.1"
serde_json = "1.0.96"
url = "2.4.0"
serde = "1.0.164"
serde_derive = "1.0.164"
console = "0.15.7"
ctrlc = "3.4.0"
home = "0.5.5"
