[package]
name = "vaultls"
version = "0.1.0"
authors = ["Pierre Millot <millotpierre3@gmail.com>"]
license = "MIT"
description = "A CLI tool to browse Hashicorp Vault secrets"
readme = "README.md"
homepage = "https://github.com/millotp/vaultls"
repository = "https://github.com/millotp/vaultls"
keywords = ["vault", "hashicorp", "cli"]
categories = ["command-line-utilities"]
edition = "2021"

[features]
default = ["native-tls"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]

[dependencies]
reqwest = { version = "0.11.18", default-features = false, features = ["blocking"] }
quick-error = "2.0.1"
serde_json = "1.0.96"
url = "2.4.0"
serde = "1.0.164"
serde_derive = "1.0.164"
console = "0.15.7"
ctrlc = "3.4.0"
home = "0.5.5"
